theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
title: "L.P. BRYANT"
trunc_title: "l.p.b.'s portfolio"
description: "seattle-based archivist and information professional"
favicon: assets/images/apple-touch-icon.png
sidebar-description: "this site acts as my portfolio and some work of which I'm most proud. check out [my github](https://github.com/zerevbrol) for related personal projects that might not have made it here to the big leagues."